repos:
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
      - id: pylint
        args:
          - --max-line-length=80
          - --ignore-imports=yes
          - -d duplicate-code
